### ISSUE TITLE
Visualize Electric Field

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-app-radiating-charge#14]
A radiobutton could be checked to visualize the electric field either as a continuous shade of colour (blue) or as discrete field lines. Particularly important for lower secondary students lacking the concept of electric field.
View electric field as : o continuous	o field lines

**Comment by hagoptaminian** [comment]
This feature unlikely to be implemented given that it is no longer being requested by the teachers. Closing the issue.
