### ISSUE TITLE
wavelength displayed along with 'spectrum bar'

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-app-radiating-charge#20]
The wavelength should be displayed along with a spectrum bar, as suggested in Sects. 1.4 of our document (see Sect. 1.5 for the wavelength-frequency relation)

**Comment by hagoptaminian** [comment]
Mockup of what the 'spectrum bar' could look like:

![Unknown-2](https://user-images.githubusercontent.com/19311953/101485322-48bbb380-395b-11eb-9ca4-ea63e357ac4e.jpeg)

**Comment by hagoptaminian** [comment]
include functionality to switch off the spectrum bar:

![image](https://user-images.githubusercontent.com/19311953/101486369-d5b33c80-395c-11eb-9dfb-ed475f15ece3.png)
